// 58 codes extracted from the API contract (global conventions table + every per-endpoint
// "Error responses" table + the scope-note in the Orders section). The plan's ~55 estimate
// undercounts DUPLICATE_VALUE / REFERENCED_BY_OTHER_RECORDS (generic catalog-admin conflicts)
// and the three return/refund codes that exist in the catalog but have no endpoint yet.
export enum ErrorCode {
  // Global — apply to every endpoint, not repeated per entry in the contract
  INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // Identity & Authentication
  INVALID_PHONE_FORMAT = 'INVALID_PHONE_FORMAT',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS = 'OTP_TOO_MANY_ATTEMPTS',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',

  // Catalog — storefront & admin (products, variants, categories, brands, attributes)
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  VARIANT_NOT_FOUND = 'VARIANT_NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  BRAND_NOT_FOUND = 'BRAND_NOT_FOUND',
  ATTRIBUTE_NOT_FOUND = 'ATTRIBUTE_NOT_FOUND',
  ATTRIBUTE_VALUE_NOT_FOUND = 'ATTRIBUTE_VALUE_NOT_FOUND',
  ATTRIBUTE_NOT_VARIANT_DEFINING = 'ATTRIBUTE_NOT_VARIANT_DEFINING',
  ATTRIBUTE_IN_USE = 'ATTRIBUTE_IN_USE',
  SLUG_ALREADY_EXISTS = 'SLUG_ALREADY_EXISTS',
  SKU_ALREADY_EXISTS = 'SKU_ALREADY_EXISTS',
  BARCODE_ALREADY_EXISTS = 'BARCODE_ALREADY_EXISTS',
  ATTRIBUTE_CODE_EXISTS = 'ATTRIBUTE_CODE_EXISTS',
  ATTRIBUTE_VALUE_CODE_EXISTS = 'ATTRIBUTE_VALUE_CODE_EXISTS',
  BRAND_SLUG_EXISTS = 'BRAND_SLUG_EXISTS',
  CATEGORY_CYCLE = 'CATEGORY_CYCLE',
  CATEGORY_NOT_EMPTY = 'CATEGORY_NOT_EMPTY',
  PRODUCT_HAS_NO_VARIANTS = 'PRODUCT_HAS_NO_VARIANTS',
  PRODUCT_MISSING_ARABIC_NAME = 'PRODUCT_MISSING_ARABIC_NAME',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  DUPLICATE_VALUE = 'DUPLICATE_VALUE',
  REFERENCED_BY_OTHER_RECORDS = 'REFERENCED_BY_OTHER_RECORDS',

  // Cart & Checkout
  STOCK_UNAVAILABLE = 'STOCK_UNAVAILABLE',
  PRODUCT_NOT_ACTIVE = 'PRODUCT_NOT_ACTIVE',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  CART_EMPTY = 'CART_EMPTY',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  GOVERNORATE_NOT_SERVED = 'GOVERNORATE_NOT_SERVED',
  SHIPPING_RATE_NOT_CONFIGURED = 'SHIPPING_RATE_NOT_CONFIGURED',
  PAYMENT_METHOD_UNAVAILABLE = 'PAYMENT_METHOD_UNAVAILABLE',
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',

  // Orders
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  // Exist in the error catalog for the future return/refund flow — no endpoint uses them yet.
  RETURN_WINDOW_CLOSED = 'RETURN_WINDOW_CLOSED',
  RETURN_QUANTITY_EXCEEDED = 'RETURN_QUANTITY_EXCEEDED',
  REFUND_EXCEEDS_ORDER_TOTAL = 'REFUND_EXCEEDS_ORDER_TOTAL',

  // Inventory
  INVENTORY_RECORD_MISSING = 'INVENTORY_RECORD_MISSING',
  CONCURRENT_STOCK_CHANGE = 'CONCURRENT_STOCK_CHANGE',
  NEGATIVE_STOCK = 'NEGATIVE_STOCK',
  MOVEMENT_TYPE_NOT_MANUAL = 'MOVEMENT_TYPE_NOT_MANUAL',
  STOCK_BELOW_RESERVED = 'STOCK_BELOW_RESERVED',
}
